services:
- docker
script:
- make
- ls -la | grep pdf
deploy:
  provider: releases
  api_key:
    secure: uHoOilWJ+C0gqziegAYfysRlwoJL6rt+HwYTxrwf4ehuAB9vCDXc91R04rwedN+eknsRQ+m6OvMadEFh138LMcjSxu4POLpyAQt+J2aUGEdtwyCWH0i64gRPQ3NA0BOSsCkRwqsXF0FyMhEFkY1UrSKkgqwTc/f8VW6uYxFli1gYRLvsaxda/xmwtZEY3e2KAbye8/2McWZdYfAKuJSXZDYHc7MuRt44LPnKkjdwbRrfQh3CHoERxk5UZHJ6L5IVRMTvwkhy2Xy/a/IAZNJBZxYWHnt4JkRpMkW6x3w54iqGw6cvMIgdhzET3kucQywuQZnP6bOJVLF3YRbAeG0Mp9ass8TWhchTGV6iv0y0mvOFObsvLI+7tmOSQAuTJDy3kkHj0bl/NokhePDsEKKK2UtOYsIyqp1+lkKY4q0QgF6Eg/ujfJn/4RsAJgg7iC449sQCtLASiGgTinLAwio6Y6FNM4MDjpGuwKkSt61DM9n2dxa8X+qzDrGz196UO1HCGm6NwrxERi8AH47+k9sfdhSnNcxxMVOp7vbKTjum29EE94Q+rzkcVj1Q/a5ErvL3Bw7O9gLu5nXOdkuj0symzWMqniu0Azp8DVMDKKjGI3su9Kjja58sRhNZIM4rfnORTFhM41OsLBzTYDUMDh8lbYGPvcVIc2tRi2YBZU7DL2E=
  file: poster.pdf
  skip_cleanup: true
  on:
    repo: uniba-ktr/PostTeX
    tags: true
